#BadAppleVideoConverter Config
#Sun Mar 29 00:09:36 HKT 2026
inputPath=./input/bad_apple.mp4
outputPath=./output/bad_apple_video.bin
targetFps=30.0
targetHeight=64
targetWidth=88
thresholdValue=127.0
