#BadAppleVideoConverter Config
#Mon Mar 30 23:24:58 HKT 2026
cannyApertureSize=3
cannyDilate=false
cannyDilateSize=2
cannyPreScale=true
cannyThreshold1=50.00
cannyThreshold2=150.00
claheClipLimit=1.5
claheEnabled=false
claheGridSize=8
inputPath=./input/bad_apple.mp4
mode=THRESHOLD
outputPath=./output/bad_apple_video.bin
targetFps=30.00
targetHeight=64
targetWidth=88
thresholdValue=127.00
usmAmount=1.2
usmEnabled=false
usmRadius=1.0
