#BadAppleVideoConverter Config
#Sun Mar 29 22:46:50 HKT 2026
cannyDilate=false
cannyDilateSize=2
cannyPreScale=true
cannyThreshold1=50.00
cannyThreshold2=150.00
inputPath=./input/rolling_girl.mp4
mode=DITHER_BAYER
outputPath=./output/rolling_girl_video.bin
targetFps=30.00
targetHeight=64
targetWidth=88
thresholdValue=127.00
